// Generated by dia2code
#ifndef STATE__BATIMENT__H
#define STATE__BATIMENT__H


namespace state {
  class Grid;
}

#include "BatimentTypeId.h"
#include "TypeId.h"
#include "Grid.h"

namespace state {

  /// class Batiment - 
  class Batiment : public state::Grid {
    // Associations
    state::BatimentTypeId batimentTypeId;
    // Attributes
  protected:
    int pv;
    int cost;
    // Operations
  public:
    Batiment (BatimentTypeId id);
    BatimentTypeId getBatimentTypeId () const;
    TypeId  getTypeId () const;
    // Setters and Getters
    void setBatimentTypeId(BatimentTypeId batimentTypeId);
    int getPv() const;
    void setPv(int pv);
    int getCost() const;
    void setCost(int cost);
  };

};

#endif
