// Generated by dia2code
#ifndef STATE__BATIMENTTYPEID__H
#define STATE__BATIMENTTYPEID__H


namespace state {

  enum BatimentTypeId {
    WATER_MILL     = 1,
    PALACE     = 2,
    SHRINE     = 3,
    PYRAMID     = 4,
    HANGING_GARDEN     = 5,
    GRANARY     = 6,
    BARRACK     = 7,
    LIBRARY     = 8
  };

};

#endif
