// Generated by dia2code
#ifndef STATE__BATIMENTTYPEID__H
#define STATE__BATIMENTTYPEID__H


namespace state {

  enum BatimentTypeId {
    baraque     = 1,
    bibliotheque     = 2,
    Amphitheatre     = 3,
    hotel     = 4,
    chateau     = 5
  };

};

#endif
