// Generated by dia2code
#ifndef STATE__BATIMENTTYPEID__H
#define STATE__BATIMENTTYPEID__H


namespace state {

  enum BatimentTypeId {
    BARAQUE     = 1,
    BIBLIOTHEQUE     = 2,
    AMPHITHEATRE     = 3,
    HOTEL     = 4,
    CHATEAU     = 5
  };

};

#endif
