// Generated by dia2code
#ifndef STATE__CATAPULT__H
#define STATE__CATAPULT__H


namespace state {
  class Mobile;
}

#include "TypeId.h"
#include "Mobile.h"

namespace state {

  /// class Catapult - 
  class Catapult : public state::Mobile {
    // Attributes
  protected:
    int combat;
    int pv     = 100;
    // Operations
  public:
    Catapult ();
    TypeId getTypeId () const;
    // Setters and Getters
    int getCombat() const;
    void setCombat(int combat);
    int getPv() const;
    void setPv(int pv);
  };

};

#endif
