// Generated by dia2code
#ifndef STATE__COLONIE__H
#define STATE__COLONIE__H


namespace state {
  class Static;
  class Batiment;
}

#include "TypeId.h"
#include "Static.h"
#include "Batiment.h"

namespace state {

  /// class Colonie - 
  class Colonie : public state::Static {
    // Associations
    // Attributes
  protected:
    int cout;
    // Operations
  public:
    Colonie ();
    TypeId getTypeId () const;
    bool isColonie () const;
    bool isWall () const;
    bool isPlateau () const;
    bool isRessource () const;
    // Setters and Getters
    int getCout() const;
    void setCout(int cout);
  };

};

#endif
