// Generated by dia2code
#ifndef STATE__COLON__H
#define STATE__COLON__H


namespace state {
  class Mobile;
}

#include "TypeId.h"
#include "Mobile.h"

namespace state {

  /// class Colon - 
  class Colon : public state::Mobile {
    // Operations
  public:
    Colon ();
    TypeId getTypeId () const;
    bool isColon () const;
    bool isMillitary () const;
    bool isCatapult () const;
    // Setters and Getters
  };

};

#endif
