// Generated by dia2code
#ifndef STATE__COLONIE__H
#define STATE__COLONIE__H

#include <vector>
#include <memory>
#include <string>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Colonie - 
  class Colonie {
    // Associations
    // Attributes
  protected:
    std::vector<std::unique_ptr<Element>> groupe;
    std::string name;
    // Operations
  public:
    Colonie ();
    void add (Element* e);
    // Setters and Getters
    const std::vector<std::unique_ptr<Element>>& getGroupe() const;
    void setGroupe(const std::vector<std::unique_ptr<Element>>& groupe);
    const std::string& getName() const;
    void setName(const std::string& name);
  };

};

#endif
