// Generated by dia2code
#ifndef STATE__COLONIE__H
#define STATE__COLONIE__H


namespace state {
  class Space;
  class Batiment;
}

#include "Space.h"
#include "Batiment.h"

namespace state {

  /// class Colonie - 
  class Colonie : public state::Space {
    // Attributes
  protected:
    int cout;
    // Operations
  public:
    Colonie ();
    SpaceTypeId const getSpaceTypeId ();
    // Setters and Getters
    int getCout() const;
    void setCout(int cout);
  };

};

#endif
