// Generated by dia2code
#ifndef STATE__COLON__H
#define STATE__COLON__H


namespace state {
  class Mobile;
}

#include "Mobile.h"

namespace state {

  /// class Colon - 
  class Colon : public state::Mobile {
    // Operations
  public:
    Colon ();
    // Setters and Getters
  };

};

#endif
