// Generated by dia2code
#ifndef STATE__DIRECTION__H
#define STATE__DIRECTION__H


namespace state {

  enum Direction {
    NONE     = 0,
    EAST     = 1,
    NORTH     = 2,
    WEST     = 3,
    SOUTH     = 4,
    NORTH_EAST     = 5,
    NORTH_WEST     = 6,
    SOUTH_EAST     = 7,
    SOUTH_WEST     = 8
  };

};

#endif
