// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>
#include <memory>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    int width;
    int height;
    std::vector<std::unique_ptr<Element>> list;
    // Operations
  public:
    ElementTab ();
    int getWidth () const;
    int getHeight () const;
    void add (Element* e);
    void resize (int width, int height);
    Element* get (int i, int j) const;
    void set (int i, int j, Element* e);
    // Setters and Getters
  };

};

#endif
