// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class ElementTab;
}

#include "TypeId.h"
#include "ElementTab.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeId typeId;
    // Attributes
  protected:
    int x;
    int y;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual TypeId getTypeId () const = 0;
    virtual bool isStatic () const = 0;
    // Setters and Getters
    void setTypeId(TypeId typeId);
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
  };

};

#endif
