// Generated by dia2code
#ifndef STATE__EVENT__H
#define STATE__EVENT__H


namespace state {

  /// class Event - 
  class Event {
    // Attributes
  public:
    int x;
    int y;
    // Operations
  public:
    Event (int x, int y);
    ~Event ();
    // Setters and Getters
  };

};

#endif
