// Generated by dia2code
#ifndef STATE__GRID__H
#define STATE__GRID__H


namespace state {
  class Static;
}

#include "Static.h"

namespace state {

  /// class Grid - 
  class Grid : public state::Static {
    // Operations
  public:
    bool isTerrain () const;
    // Setters and Getters
  };

};

#endif
