// Generated by dia2code
#ifndef STATE__JOUEUR__H
#define STATE__JOUEUR__H

#include <vector>
#include <memory>

namespace state {
  class Colonie;
}

#include "Colonie.h"

namespace state {

  /// class Joueur - 
  class Joueur {
    // Associations
    // Attributes
  protected:
    int id ;
    std::vector<std::unique_ptr<Colonie>> listColonies;
    // Operations
  public:
    Joueur (int i);
    void addCity (Colonie* c);
    // Setters and Getters
    int getId () const;
    void setId (int id );
    const std::vector<std::unique_ptr<Colonie>>& getListColonies() const;
    void setListColonies(const std::vector<std::unique_ptr<Colonie>>& listColonies);
  };

};

#endif
