// Generated by dia2code
#ifndef STATE__MILITARY__H
#define STATE__MILITARY__H


namespace state {
  class Mobile;
}

#include "MilTypeId.h"
#include "TypeId.h"
#include "Mobile.h"

namespace state {

  /// class Military - 
  class Military : public state::Mobile {
    // Associations
    state::MilTypeId milTypeId;
    // Attributes
  protected:
    int combat;
    int pv     = 100;
    // Operations
  public:
    Military (MilTypeId id);
    TypeId getTypeId () const;
    // Setters and Getters
    MilTypeId getMilTypeId() const;
    void setMilTypeId(MilTypeId milTypeId);
    int getCombat() const;
    void setCombat(int combat);
    int getPv() const;
    void setPv(int pv);
  };

};

#endif
