// Generated by dia2code
#ifndef STATE__MILLTYPEID__H
#define STATE__MILLTYPEID__H


namespace state {

  enum MillTypeId {
    epeiste     = 1,
    mitrailleur     = 2,
    mousquetaire     = 3
  };

};

#endif
