// Generated by dia2code
#ifndef STATE__MILTYPEID__H
#define STATE__MILTYPEID__H


namespace state {

  enum MilTypeId {
    EPEISTE     = 1,
    MITRAILLEUR     = 2,
    MOUSQUETAIRE     = 3,
    CATAPULT     = 4
  };

};

#endif
