// Generated by dia2code
#ifndef STATE__MOBILE__H
#define STATE__MOBILE__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Mobile - 
  class Mobile : public state::Element {
    // Attributes
  protected:
    int point_mouvement;
    int cout;
    int position;
    // Operations
  public:
    Mobile ();
    bool isStatic () const;
    // Setters and Getters
    int getPoint_mouvement() const;
    void setPoint_mouvement(int point_mouvement);
    int getCout() const;
    void setCout(int cout);
    int getPosition() const;
    void setPosition(int position);
  };

};

#endif
