// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class Observer;
  class Event;
}

#include "Observer.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  private:
    mutable std::vector<Observer*> observers;
    // Operations
  public:
    ~Observable ();
    void registerObserver (Observer* o) const;
    void unregisterObserver (Observer* o) const;
    void notifyObservers (const Event& e) const;
    // Setters and Getters
  };

};

#endif
