// Generated by dia2code
#ifndef STATE__PAYSAGE__H
#define STATE__PAYSAGE__H


namespace state {
  class Grid;
}

#include "PaysageTypeId.h"
#include "TypeId.h"
#include "Grid.h"

namespace state {

  /// class Paysage - 
  class Paysage : public state::Grid {
    // Associations
    state::PaysageTypeId paysageTypeId;
    // Attributes
  public:
     ;
    // Operations
  public:
    Paysage (PaysageTypeId id);
    TypeId getTypeId () const;
    // Setters and Getters
    PaysageTypeId getPaysageTypeId() const;
    void setPaysageTypeId(PaysageTypeId paysageTypeId);
  };

};

#endif
