// Generated by dia2code
#ifndef STATE__PAYSAGETYPEID__H
#define STATE__PAYSAGETYPEID__H


namespace state {

  enum PaysageTypeId {
    FORET1     = 1,
    FORET2     = 2,
    PLANTE1     = 3,
    COLLINE1     = 4,
    MONTAGNE1     = 5
  };

};

#endif
