// Generated by dia2code
#ifndef STATE__PLATEAU__H
#define STATE__PLATEAU__H


namespace state {
  class Static;
}

#include "PlateauTypeId.h"
#include "Static.h"

namespace state {

  /// class Plateau - 
  class Plateau : public state::Static {
    // Associations
    state::PlateauTypeId plateauTypeId;
    // Operations
  public:
    Plateau (PlateauTypeId id);
    TypeId const getTypeId ();
    PlateauTypeId const getPlateauTypeId ();
    // Setters and Getters
    void setPlateauTypeId(PlateauTypeId plateauTypeId);
  };

};

#endif
