// Generated by dia2code
#ifndef STATE__PLATEAUTYPEID__H
#define STATE__PLATEAUTYPEID__H


namespace state {

  enum PlateauTypeId {
    cote     = 1,
    desert     = 2,
    plaine     = 3,
    montagne     = 4,
    ocean     = 5
  };

};

#endif
