// Generated by dia2code
#ifndef STATE__PLATEAUTYPEID__H
#define STATE__PLATEAUTYPEID__H


namespace state {

  enum PlateauTypeId {
    EMPTY     = 1,
    PLAINE     = 2,
    COTE     = 3,
    DESERT     = 4,
    MONTAGNE     = 5,
    OCEAN     = 6
  };

};

#endif
