// Generated by dia2code
#ifndef STATE__PLATEAUTYPEID__H
#define STATE__PLATEAUTYPEID__H


namespace state {

  enum PlateauTypeId {
    empty     = 1,
    plaine     = 2,
    cote     = 3,
    desert     = 4,
    montagne     = 5,
    ocean     = 6
  };

};

#endif
