// Generated by dia2code
#ifndef STATE__PLATEAU__H
#define STATE__PLATEAU__H


namespace state {
  class Space;
}

#include "PlateauTypeId.h"
#include "Space.h"

namespace state {

  /// class Plateau - 
  class Plateau : public state::Space {
    // Associations
    state::PlateauTypeId plateautypeId;
    // Operations
  public:
    Plateau (PlateauTypeId id);
    SpaceTypeId const getSpaceTypeId ();
    // Setters and Getters
    PlateauTypeId getPlateautypeId() const;
    void setPlateautypeId(PlateauTypeId plateautypeId);
  };

};

#endif
