// Generated by dia2code
#ifndef STATE__RESSOURCE__H
#define STATE__RESSOURCE__H

#include <string>

namespace state {
  class Static;
}

#include "RessourceTypeId.h"
#include "Static.h"

namespace state {

  /// class Ressource - 
  class Ressource : public state::Static {
    // Associations
    state::RessourceTypeId ressourceTypeId;
    // Attributes
  protected:
    std::string name;
    // Operations
  public:
    Ressource (RessourceTypeId id);
    TypeId const getTypeId ();
    RessourceTypeId const getRessourceTypeId ();
    // Setters and Getters
    void setRessourceTypeId(RessourceTypeId ressourceTypeId);
    const std::string& getName() const;
    void setName(const std::string& name);
  };

};

#endif
