// Generated by dia2code
#ifndef STATE__RESSOURCETYPEID__H
#define STATE__RESSOURCETYPEID__H


namespace state {

  enum RessourceTypeId {
    cheval     = 1,
    charbon     = 2,
    fer     = 3,
    vin     = 4
  };

};

#endif
