// Generated by dia2code
#ifndef STATE__RESSOURCETYPEID__H
#define STATE__RESSOURCETYPEID__H


namespace state {

  enum RessourceTypeId {
    CHEVAL     = 1,
    CHARBON     = 2,
    FER     = 3,
    VIN     = 4
  };

};

#endif
