// Generated by dia2code
#ifndef STATE__RESSOURCE__H
#define STATE__RESSOURCE__H


namespace state {
  class Static;
}

#include "RessourceTypeId.h"
#include "TypeId.h"
#include "Static.h"

namespace state {

  /// class Ressource - 
  class Ressource : public state::Static {
    // Associations
    state::RessourceTypeId ressourceTypeId;
    // Operations
  public:
    Ressource (RessourceTypeId id);
    TypeId getTypeId () const;
    // Setters and Getters
    RessourceTypeId getRessourceTypeId() const;
    void setRessourceTypeId(RessourceTypeId ressourceTypeId);
  };

};

#endif
