// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeId {
    Plateau     = 1,
    Colonie     = 2,
    Ressource     = 3
  };

};

#endif
