// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Static;
}

#include "SpaceTypeId.h"
#include "Static.h"

namespace state {

  /// class Space - 
  class Space : public state::Static {
    // Associations
    // Operations
  public:
    Space (SpaceTypeId id);
    TypeId const getTypeId ();
    bool const isSpace ();
    virtual SpaceTypeId const getSpaceTypeId () = 0;
    // Setters and Getters
  };

};

#endif
