// Generated by dia2code
#ifndef STATE__SPACE__H
#define STATE__SPACE__H


namespace state {
  class Static;
}

#include "Static.h"
#include "SpaceTypeId.h"

namespace state {

  /// class Space - 
  class Space : public state::Static {
    // Associations
    state::SpaceTypeId spacetypeId;
    // Operations
  public:
    TypeId const getTypeId ();
    bool const isSpace ();
    virtual SpaceTypeId const getSpaceTypeId () = 0;
    // Setters and Getters
    SpaceTypeId getSpacetypeId() const;
    void setSpacetypeId(SpaceTypeId spacetypeId);
  };

};

#endif
