// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab grid;
    ElementTab chars;
    // Operations
  public:
    ElementTab& getGrid ();
    ElementTab& getChars ();
    // Setters and Getters
  };

};

#endif
