// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class ElementTab;
  class Joueur;
  class Observable;
}

#include "ElementTab.h"
#include "Observable.h"
#include "Joueur.h"

namespace state {

  /// class State - 
  class State : public state::Observable {
    // Associations
    // Attributes
  private:
    ElementTab terrain;
    ElementTab grid;
    ElementTab chars;
    std::vector<Joueur*> listJoueur;
    int number;
    // Operations
  public:
    ElementTab& getGrid ();
    const ElementTab& getGrid () const;
    int getNumber () const;
    ElementTab& getChars ();
    const ElementTab& getChars () const;
    ElementTab& getTerrain ();
    const ElementTab& getTerrain () const;
    void addJoueur (Joueur* j);
    void setNumber (int n);
    // Setters and Getters
  };

};

#endif
