// Generated by dia2code
#ifndef STATE__TERRAINTYPEID__H
#define STATE__TERRAINTYPEID__H


namespace state {

  enum TerrainTypeId {
    PLAINE     = 1,
    DESERT     = 2,
    NEIGE     = 3,
    MOUNTAIN,
    OCEAN     = 5
  };

};

#endif
