// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    Ressource     = 1,
    Techno     = 2,
    Plateau     = 3,
    Colonies     = 4,
    Wall     = 5,
    Colon     = 6,
    Millitary     = 7,
    Catapult     = 8
  };

};

#endif
