// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    COLON     = 1,
    MILITARY     = 2,
    TERRAIN     = 3,
    BATIMENT     = 4,
    RESSOURCE     = 5,
    PAYSAGE     = 6
  };

};

#endif
