// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    Catapult     = 1,
    Space     = 2,
    Wall     = 3,
    Colon     = 4,
    Millitary     = 5
  };

};

#endif
