// Generated by dia2code
#ifndef RENDER__CHARSLAYER__H
#define RENDER__CHARSLAYER__H


namespace state {
  class ElementTab;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/ElementTab.h"

namespace render {

  /// class CharsLayer - 
  class CharsLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::ElementTab& tab;
    // Operations
  public:
    CharsLayer (const state::ElementTab& tab);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
