// Generated by dia2code
#ifndef RENDER__GRIDTILESET__H
#define RENDER__GRIDTILESET__H

#include <vector>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class GridTileSet - 
  class GridTileSet : public render::TileSet {
    // Attributes
  public:
    std::vector<Tile> plateau;
    std::vector<Tile> ressource;
    std::vector<Tile> wall;
    std::vector<Tile> colonie;
    // Operations
  public:
    GridTileSet ();
    int getCellWidth () const;
    int getCellHeight () const;
    int getImageFile () const;
    virtual const Tile& getTile (const state::Element& e) const;
    // Setters and Getters
  };

};

#endif
