// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H


namespace state {
  class State;
  class ElementTab;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::State& state;
    // Operations
  public:
    StateLayer (const state::ElementTab& state);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
