// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Command;
  class Engine;
}

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    void listCommands (state::State& state, std::vector<engine::Command*> list);
    virtual void run  (engine::Engine& engine) = 0;
    // Setters and Getters
  };

};

#endif
