// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <random>

namespace ai {
  class PathMap;
};
namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  private:
    std::mt19937 randgen;
    PathMap unitJoueur1Map;
    PathMap unitJoueur2Map;
    PathMap batJoueur1Map;
    PathMap batJoueur2Map;
    // Operations
  public:
    HeuristicAI (state::State& state);
    const PathMap& getUnitJoueur1Map () const;
    const PathMap& getUnitJoueur2Map () const;
    const PathMap& getBatJoueur1Map () const;
    const PathMap& getBatJoueur2Map () const;
    void run (engine::Engine& engine);
    // Setters and Getters
  };

};

#endif
