// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <random>

namespace ai {
  class PathMap;
};
namespace state {
  class State;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "PathMap.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  public:
    PathMap joueur1Map;
    PathMap joueur2Map;
  private:
    std::mt19937 randgen;
    // Operations
  public:
    HeuristicAI (const state::State& state);
    void run (engine::Engine& engine);
    // Setters and Getters
  };

};

#endif
