// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <random>

namespace engine {
  class Engine;
  class EngineClient;
};
namespace ai {
  class AI;
}

#include "AI.h"
#include "engine/EngineClient.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  private:
    std::mt19937 randgen;
    // Operations
  public:
    RandomAI ();
    void stateChanged (const state::Event& event);
    void run (engine::Engine& engine);
    void runReplay (engine::Engine& engine);
    void runClient (engine::EngineClient& engine);
    // Setters and Getters
  };

};

#endif
