// Generated by dia2code
#ifndef ENGINE__ATTAQUECOMMAND__H
#define ENGINE__ATTAQUECOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AttaqueCommand - 
  class AttaqueCommand : public engine::Command {
    // Operations
  public:
    void attaque (state::State& state);
    CommandeTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
