// Generated by dia2code
#ifndef ENGINE__ATTAQUECOMMAND__H
#define ENGINE__ATTAQUECOMMAND__H


namespace state {
  class Millitary;
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/Millitary.h"

namespace engine {

  /// class AttaqueCommand - 
  class AttaqueCommand : public engine::Command {
    // Attributes
  private:
    int x;
    int y;
    int x1;
    int y1;
    // Operations
  public:
    AttaqueCommand (int x, int y, int x1, int y1);
    void attaque (state::Millitary* m, state::Millitary* m1);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
