// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <stack>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "CommandTypeId.h"
#include "state/State.h"
#include "Action.h"

namespace engine {

  /// class Command - 
  class Command {
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getTypeId () const = 0;
    virtual void execute (state::State& state, std::stack<Action*>& s) = 0;
    virtual void serialized (Json::Value& out) const = 0;
    // Setters and Getters
  };

};

#endif
