// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 0,
    MOVE     = 1,
    ATTAQUE     = 2,
    FONDA     = 3
  };

};

#endif
