// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 0,
    ORIENTATION     = 1,
    ATTAQUE     = 4,
    FONDA     = 5
  };

};

#endif
