// Generated by dia2code
#ifndef ENGINE__ENGIME__H
#define ENGINE__ENGIME__H

#include <map>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"
#include "Command.h"

namespace engine {

  /// class Engime - 
  class Engime {
    // Associations
    // Attributes
  private:
    state::State currentState;
    std::map<int,std::unique_ptr<Command>> currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
    const state::State& getState ();
    void addPassiveCommands ();
    void addCommand (int priority, Command* cmd);
    void update ();
    // Setters and Getters
  };

};

#endif
