// Generated by dia2code
#ifndef ENGINE__FONDATIONCOMMAND__H
#define ENGINE__FONDATIONCOMMAND__H

#include <stack>
#include <json/json.h>

namespace state {
  class Colon;
  class State;
};
namespace engine {
  class Action;
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/Colon.h"

namespace engine {

  /// class FondationCommand - 
  class FondationCommand : public engine::Command {
    // Operations
  public:
    void fonda (state::Colon* c);
    CommandTypeId getTypeId () const;
    void execute (state::State& state, std::stack<Action*>& s);
    void serialized (Json::Value& out) const;
    // Setters and Getters
  };

};

#endif
