// Generated by dia2code
#ifndef ENGINE__HANDLECOLLISIONSCOMMAND__H
#define ENGINE__HANDLECOLLISIONSCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class HandleCollisionsCommand - 
  class HandleCollisionsCommand : public engine::Command {
    // Operations
  public:
    void execute (state::State& state);
    CommandeTypeId getTypeId () const;
    void TestCollisions ();
    // Setters and Getters
  };

};

#endif
