// Generated by dia2code
#ifndef ENGINE__HANDLEFONDATIONCOMMAND__H
#define ENGINE__HANDLEFONDATIONCOMMAND__H


namespace state {
  class Colon;
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "state/Colon.h"

namespace engine {

  /// class HandleFondationCommand - 
  class HandleFondationCommand : public engine::Command {
    // Operations
  public:
    void TestFonda (state::Colon& c);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
