// Generated by dia2code
#ifndef ENGINE__KILLACTION__H
#define ENGINE__KILLACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
};
namespace state {
  class Military;
}

#include "state/MilTypeId.h"
#include "Action.h"
#include "state/Military.h"

namespace engine {

  /// class KillAction - 
  class KillAction : public engine::Action {
    // Attributes
  protected:
    int x;
    int y;
    int x1;
    int y1;
    state::MilTypeId tmp;
    // Operations
  public:
    KillAction (int x, int y, int x1, int y1);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getX1() const;
    void setX1(int x1);
    int getY1() const;
    void setY1(int y1);
    state::MilTypeId getTmp() const;
    void setTmp(state::MilTypeId tmp);
  };

};

#endif
