// Generated by dia2code
#ifndef ENGINE__OBSERVER__H
#define ENGINE__OBSERVER__H


namespace engine {

  /// class Observer - 
  class Observer {
    // Operations
  public:
    virtual void engineUpdating () = 0;
    virtual void engineUpdated () = 0;
    // Setters and Getters
  };

};

#endif
