// Generated by dia2code
#ifndef SERVER__COMMANDSSERVICE__H
#define SERVER__COMMANDSSERVICE__H

#include <vector>
#include <json/json.h>

namespace engine {
  class Command;
};
namespace server {
  class Commande;
  class AbstractService;
}

#include "Commande.h"
#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class CommandsService - 
  class CommandsService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    std::vector<engine::Command*> commands;
    std::vector<Commande> commandes;
    // Operations
  public:
    CommandsService ();
    HttpStatus get (Json::Value& out, int id) const;
    HttpStatus put (Json::Value& out, const Json::Value& in);
    // Setters and Getters
  };

};

#endif
