// Generated by dia2code
#ifndef SERVER__COMMANDE__H
#define SERVER__COMMANDE__H

#include <string>

namespace server {

  /// class Commande - 
  class Commande {
    // Attributes
  public:
    int name;
    int x;
    int y;
    int x1;
    int y1;
    std::string terrain;
    std::string grid;
    // Operations
  public:
    Commande (int name, int x, int y, int x1, int y1, std::string terrain, std::string grid);
    // Setters and Getters
  };

};

#endif
