// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace ai {
  class RandomAI;
};
namespace engine {
  class Observer;
};
namespace render {
  class TerrainLayer;
  class CharsLayer;
  class GridLayer;
}

#include "ai/RandomAI.h"
#include "engine/Observer.h"
#include "render/TerrainLayer.h"
#include "render/CharsLayer.h"
#include "render/GridLayer.h"

namespace client {

  /// class Client - 
  class Client : public engine::Observer {
    // Associations
    // Attributes
  private:
    ai::RandomAI random;
    state::State state;
    // Operations
  public:
    Client ();
    void engineUpated ();
    void engineUpdating ();
    void run ();
    // Setters and Getters
  };

};

#endif
