// Generated by dia2code
#ifndef CLIENT__ENGINECLIENT__H
#define CLIENT__ENGINECLIENT__H


namespace engine {
  class Command;
  class Engine;
}

#include "engine/Engine.h"

namespace client {

  /// class EngineClient - 
  class EngineClient : public engine::Engine {
    // Attributes
  protected:
    int epoch;
    // Operations
  public:
    void addCommand (engine::Command* cmd);
    void runThread (ai::AI* random);
    // Setters and Getters
    int getEpoch() const;
    void setEpoch(int epoch);
  };

};

#endif
