// Generated by dia2code
#ifndef CLIENT__NETWORKCLIENT__H
#define CLIENT__NETWORKCLIENT__H

#include <string>

namespace engine {
  class EngineClient;
};
namespace state {
  class State;
};
namespace ai {
  class RandomAI;
};
namespace render {
  class GridLayer;
  class CharsLayer;
  class TerrainLayer;
}

#include "engine/EngineClient.h"
#include "state/State.h"
#include "ai/RandomAI.h"
#include "render/GridLayer.h"
#include "render/CharsLayer.h"
#include "render/TerrainLayer.h"

namespace client {

  /// class NetworkClient - 
  class NetworkClient {
    // Attributes
  private:
    std::string url;
    int port;
    int character;
    // Operations
  public:
    NetworkClient (const std::string& url, int port, int character);
    void run ();
  protected:
    std::string getGameStatus ();
    // Setters and Getters
  };

};

#endif
