// Generated by dia2code
#ifndef CLIENT__NETWORKCLIENT__H
#define CLIENT__NETWORKCLIENT__H

#include <string>
#include <memory>
#include <json/json.h>

namespace client {
  class EngineClient;
};
namespace ai {
  class RandomAI;
};
namespace engine {
  class Command;
};
namespace render {
  class GridLayer;
  class CharsLayer;
  class TerrainLayer;
}

#include "ai/RandomAI.h"
#include "render/GridLayer.h"
#include "render/CharsLayer.h"
#include "render/TerrainLayer.h"
#include "engine/Command.h"
#include "EngineClient.h"

namespace client {

  /// class NetworkClient - 
  class NetworkClient {
    // Associations
    // Attributes
  private:
    std::string url;
    int port;
    int character;
    EngineClient& engine;
    std::unique_ptr<ai::RandomAI> player_ai;
    // Operations
  public:
    NetworkClient (EngineClient& engine, const std::string& url, int port, int character);
    void run ();
  protected:
    std::string getGameStatus ();
    bool getServerCommands (Json::Value& out);
    void putServerCommand (engine::Command* command);
    // Setters and Getters
  };

};

#endif
